version: '3.5'

services:
    back:
        build: _back/ 
        ports:
          - 8080:8080
        container_name: back
        
    front:
        build: _front/
        ports:
          - 5000:5000
        volumes:
          - ./_front/src:/usr/src/app/src

        container_name: front

    redis_db:
        image: redis:latest
        container_name: redis_db
        