version: '3.5'

services:
    back:
        build: _back/ 
        ports:
          - 8080:8080
        container_name: back
        
    front:
        build: _front/
        ports:
          - 5000:5000
        volumes:
          - ./_front/src/App.js:/usr/src/app/src/App.js

        container_name: front
        