version: '3.5'

services:
    back:
        build: _back/ 
        ports:
            - 8080:8080
        container_name: back
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=example
            - POSTGRES_DATABASE=postgres
        
    front:
        build: _front/
        ports:
            - 5000:5000
        container_name: front

    redis:
        image: redis:latest
        container_name: redis

    postgres:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: example
        container_name: postgres